# Generated by Django 5.1.5 on 2025-02-10 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idol',
            name='stage_name',
            field=models.CharField(max_length=100),
        ),
    ]
